name: TDCC Crawler

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

permissions:
  contents: write   # ⭐ 關鍵

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: 下載程式碼
        uses: actions/checkout@v3

      - name: 安裝 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安裝 Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: 安裝套件
        run: pip install -r requirements.txt

      - name: 執行爬蟲
        run: python tdcc_stock_crawler.py

      - name: Commit CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add *.csv
          git commit -m "auto update data" || echo "no changes"
          git push
